= 萌新指北

本章将简略介绍PD2中的主要玩法。

== 手工

手工就是根据配方合成装备，允许在固定几条词缀的基础上随机分配其他词缀。

使用手工配方可以在游戏前期轻松合成基础装备，一些合(海)理(景)搭(房)配词缀的手工装备更是能成为某些BD的毕业(GG)装备。

需要注意的是，PD2在原版的基础上对手工合成进行了很多优化。例如:

* 不再限制装备底材，无论是什么底材的装备都能使用该装备部位的任意配方；
* 黄金物品也能使用手工配方进行合成；
* 添加了一些新的手工配方：吸血、丰饶、闪耀。

详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Crafting[手工介绍]。

== 腐化

腐化是PD2在原版基础上做出的更新，类似 https://poe.qq.com[POE(流放之路)] 的“瓦尔系统”，需要消耗世界之石碎片在魔盒内进行合成。

详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Corruptions[腐化介绍]。

需要注意的是，腐化不光可以针对装备，也可以针对T图。

同时，毁灭小护身符也可以进行腐化，不过所需材料是拉斯玛(俗称"大马")掉落的"暗之世界石碎片"。

== 我应该刷哪？

刷刷刷是暗黑like游戏的核心，在接触一款暗黑like游戏时，萌新最开始要了解的就是应该刷哪里。

这里推荐一些热门场景：

* BD成型前的farm地点
** 噩梦BOSS
** 地穴(地狱-A1泰摩高地的洞穴)
** 矫正者/督军山客(噩梦/地狱-A5第一个传送点上下两波怪)
** 古代通道(地狱-A2失落城市洞穴)(冰法)
** 冥河之洞(A5亚瑞特高原红门)(电系)
* 有一定装备基础后的farm地点
** 地狱超市(A4混沌庇护所)
** 地狱牛场(通关后A1用怀特假腿和回城卷合成红门)
** 地狱巴尔(A5毁灭王座)
** T1地图
** 组队刷T2/T3地图

需要注意的是，PD2中A1BOSS安达利尔(俗称安姐)使用的是A3BOSS墨菲斯托相同的掉落；
A2BOSS督瑞尔(虫子)使用的是A5BOSS巴尔相同的掉落。

而由于法师在前期可以卡位无伤杀虫子，虫子又和巴尔相同掉落。
所以法师在开荒的时候，用火墙卡位刷虫子(地狱)是前期积累基础装备(俗称日用品)的一个非常好的选择。

== 地图

地图(俗称T图)，是PD2在原版基础上做出的更新，类似 https://poe.qq.com[POE(流放之路)] 的“异界地图”，是游戏中很重要的一个farm场景。 详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Maps[地图介绍]。

T图分为T1、T2、T3以及特殊的T4四个等级。场景等级分别为87/88/89/90级。
T图与原版游戏相比，区域等级更高，能够出游戏的全部物品，所以也是游戏后期主要的farm场景。

一般来说，打造能够效率单刷T图(T3+亮金+腐化)的BD，是玩家在游戏前中期的一个重要目标。

=== 地图进入条件

80级以上，并且击败过远古野蛮人(3BB)的角色，在A5城镇中邮件点击地图物品，即可打开特殊地图的传送红门。

每局游戏中只能开启一个特殊地图，在刷完之后需要重建房间再次开启。

=== 地图的获取

从噩梦难度第五幕起，金怪开始有几率掉落T图；第一次完成地狱难度救安雅的任务后，也会固定赠送一张T1难度的地图。


1111

- 手工
- 腐化
- 刷哪
    - 装备成型前
        - 噩梦BOSS
        - 地穴(地狱)
        - 矫正者/督军山客(噩梦/地狱)
        - 古代通道(地狱)(冰法)
        - 冥河之洞(电系)
    - 成型后
        - 地狱超市
        - 地狱牛场
        - 地狱巴尔
        - T1地图
        - 组队刷T2/T3地图
- 地图
- 新3BB
- 6BOSS
    - 女伯爵(A1-遗忘之塔)、血鸦(A1-埋骨之地)
    - 召唤者(A2-神秘庇护所)、疯狂血腥女巫(A2-死亡之殿第三层)
    - 尼拉塞克(A5-安雅红门)、衣卒尔(A4-绝望平原)
- 大黑毛
- 拉斯玛

== 参考资料

* link:https://www.reddit.com/r/ProjectDiablo2/comments/mrsf67/guide_endgame_basics_to_pd2[reddit帖子:[Guide\] End-Game Basics to PD2]
* link:https://wiki.projectdiablo2.cn/wiki/%E9%A6%96%E9%A1%B5[PD2国服Wiki]
* link:https://qm.qq.com/cgi-bin/qm/qr?k=cgdOh0UaPRz1bEBBG3-o9EQVtkq6cSgv&jump_from=webapi[QQ群(693091795)] 内大佬指点
