= 萌新指北

本章将简略介绍PD2中的主要玩法，给萌新一个入门引导。

== 手工

手工就是根据配方合成装备，允许在固定几条词缀的基础上随机分配其他词缀，手工是原版暗黑破坏神2毁灭之王(LoD)就有的系统。

需要注意的是，PD2在原版的基础上对手工合成进行了很多优化。例如:

* 不再限制装备底材，无论是什么底材的装备都能使用该装备部位的任意配方；
* 黄金物品也能使用手工配方进行合成；
* 添加了一些新的手工配方：吸血、丰饶、闪耀。

使用手工配方可以在游戏前期轻松合成基础装备，一些合(海)理(景)搭(房)配词缀的手工装备更是能成为某些BD的毕业(GG)装备。

详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Crafting[手工介绍,window=_blank]。

== 腐化

腐化是PD2新增的内容，类似 https://poe.qq.com[POE(流放之路),window=_blank] 的“瓦尔系统”，需要消耗世界之石碎片在魔盒内进行合成。

详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Corruptions[腐化介绍,window=_blank]。

需要注意的是，腐化不光可以针对装备，也可以针对T图。

同时，毁灭小护身符也可以进行腐化，不过所需材料是拉斯玛(俗称"大马")掉落的"暗之世界石碎片"。

== 我应该刷哪？

刷刷刷是暗黑like游戏的核心，在接触一款暗黑like游戏时，萌新最开始要了解的就是应该刷哪里。

这里推荐一些热门地点：

=== BD成型前的farm地点

* 噩梦BOSS
* 地穴(地狱-A1泰摩高地的洞穴)
* 大陵寝/墓地(地狱-A1埋骨之地)(火球)
* 古代通道(地狱-A2失落城市洞穴)(冰法)
* 地狱A2BOSS督瑞尔(法师卡位杀)
* 矫正者/督军山克(噩梦/地狱-A5第一个传送点上下各有一波怪)
* 冥河之洞(A5亚瑞特高原红门)(电系)

这里面大部分是比较好打的85级场景，怪物难度不高，前期比较好打。

需要注意的是，在PD2中，A1BOSS安达利尔(俗称安姐)使用的是A3BOSS墨菲斯托(劳模)相同的掉落； A2BOSS督瑞尔(虫子)使用的是A5BOSS巴尔相同的掉落。

而由于法师在前期可以卡位无伤杀虫子，虫子又和巴尔相同掉落。 所以法师在开荒的时候，用火墙卡位刷虫子(地狱)是前期积累基础装备(俗称日用品)的一个非常好的选择。

=== 有一定装备基础后的farm地点

* 地狱超市(A4混沌庇护所)
* 地狱牛场(通关后A1用怀特假腿和回城卷合成红门)
* 地狱巴尔(A5毁灭王座)
* T1地图
* 组队刷T2/T3地图
* <<small-black,超级暗黑破坏神(小黑)>>

=== 游戏后期的farm地点以及挑战

* T3地图(包括暗金地图)
* <<new-3bb,超级古代人(新3BB)>>
* <<six-boss,超级崔斯特瑞姆(6BOSS)>>
* <<big-black,超级暗黑破坏神(大黑)>>
* <<rathma,拉斯玛(大马)>>
* T4地图

[[map]]
== 地图

地图(俗称T图)，是PD2新增的内容，类似 https://poe.qq.com[POE(流放之路),window=_blank] 的“异界地图系统”，是游戏中很重要的一个farm场景。 详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Maps[地图介绍,window=_blank]。

T图分为T1、T2、T3以及极难的T4四个等级。场景等级分别为87/88/89/90级。 T图与原版游戏相比，区域等级更高，能够出游戏的全部物品，所以也是游戏后期主要的farm场景。

一般来说，打造能够效率单刷T图(T3+亮金+腐化)的BD，是玩家在游戏前中期的一个重要目标。

=== 地图进入条件

80级以上，并且击败过原版剧情中的远古野蛮人(3BB)的角色，在A5城镇中右键点击地图，即可打开特殊地图的传送红门。

每局游戏中只能开启一个地图，在刷完之后需要重建房间再次开启。

=== 地图的获取

从噩梦难度第五幕起，精英怪开始有几率掉落T图；第一次完成地狱难度救安雅的任务后，也会固定赠送一张T1难度的地图。

在地图中打怪更容易掉落地图，也有几率出现更高级别的地图。

一般来说，一旦你开始farm地图，地图就不会缺少了(起码T1地图是这样-_-!)，一般不需要去野外找精英怪刷地图。

=== 地图修改

地图的词缀系统非常复杂，请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Maps[地图介绍,window=_blank]。

一般我们会刷**T3+亮金+腐化**这样的地图，同时避免随机到那些困难的词缀。

如果一张地图有一些我们不想面对的词缀，我们也可以通过 *毁灭法珠* 将地图还原成白色普通地图重新进行修改，详情请查看 https://wiki.projectdiablo2.cn/wiki/Recipes#%E5%9C%B0%E5%9B%BE[Wiki->合成->消耗品->地图,window=_blank] 章节。

有些BD针对单体怪物的能力较强，AOE能力却比较弱势，这时候可以用道具 *强化法珠* (安雅处购买)与该地图在魔盒中进行合成。 合成后地图的怪物数量减半，获得的奖励翻倍，同时怪物也会适当的加强，但不会影响地图的事件。

[[new-3bb]]
== 超级古代人(新3BB)

原版亚瑞特山脉巅峰马道克、塔里克和科里克这3个野蛮人一般被玩家称为3BB，PD2以之为蓝本新增了一个场景。

新3BB与原版相比更为强大，同时增加了掉落(原版是没有掉落的)。

新3BB可以在开始战斗前切换雕像，选择与哪几个野蛮人进行战斗。在战斗胜利后，每个野蛮人会掉落一个英雄旗帜。

新3BB难度较高，奖励也极其丰富，会掉落大量装备包括暗金和套装，是游戏中后期不能错过的farm场景。
https://b23.tv/LGKzmwH[这里,window=_blank] 是我在S9赛季录制的一场3BB视频。

NOTE: 据我个人的不准确观测，新3BB掉落“大货”的几率很高。像技能腰带、4神器这种爆率较低的物品，在新3BB经常掉落，上面链接中的视频就掉落了“次元”。

=== 如何进入

进入3BB需要提前准备好 *古代人的遗物* ，也就是门票，在A5哈洛加斯城镇中的血喷泉(就是安雅左边的那个红盆)附近右键使用后进入。

*古代人的遗物* 是T1、T2以及T3<<map,地图>>中分别掉落的三种印记，在魔盒中合成出来的。三种印记的掉落几率是：

* *马道克的印记*：T1地图怪物1:12K几率掉落
* *塔里克的印记*：T2地图怪物1:10K几率掉落
* *科里克的印记*：T3地图怪物1:8K几率掉落

[[six-boss]]
== 超级崔斯特瑞姆(6BOSS)

6BOSS是原版就有的系统，击败最终BOSS后会获得 *火炬* 护身符，增加随机职业的2点技能，是游戏中非常重要的物品，基本上每个BD都需要它。

由于整个流程需要与6个BOSS进行战斗，所以被玩家称为6BOSS。

=== 门票获取

PD2针对6BOSS做出了一些优化。

首先就是增加了掉落门票的怪物：

* *恐惧之钥*：女伯爵(A1-遗忘之塔)1:11几率掉落、血鸦(A1-埋骨之地)1:9几率掉落
* *憎恨之钥*：召唤者(A2-神秘庇护所)1:8几率掉落、疯狂血腥女巫(A2-死亡之殿第三层)1:9几率掉落
* *毁灭之钥*：尼拉塞克(A5-安雅红门)1:8几率掉落、衣卒尔(A4-绝望平原)1:9几率掉落

其次在 *地图-黑暗尖塔* 事件中会有几率掉落钥匙，每张地图最多掉落6把钥匙。 这也是我最推荐的farm钥匙的途径，因为你可以在farmT图的过程中顺便就刷到了钥匙。

=== 6BOSS流程

* 当我们分别获取3种钥匙各3把，也就是一共9把钥匙后，就可以开启6BOSS战斗了。
* 在地狱难度A5哈洛加斯城镇中开启，开启办法是将任意3种钥匙各1把，放在魔盒中合成，即可开启一个红色传送门。 红色传送门有3种，分别是 *痛苦熔炉(BOSS为混沌衣卒尔)*、*主母巢穴(BOSS为莉莉丝)*、*遗忘沙漠(BOSS为混沌督瑞尔)*，打开哪个传送门是随机的，但在同一局游戏中不会重复出现。所以我们一般会在同一局游戏中开启这三个红门。
* 分别击败这三个BOSS，**衣卒尔**会掉落**墨菲斯托之脑**，**莉莉丝**会掉落**暗黑破坏神之角**，**督瑞尔**会掉落**巴尔之眼**。将这三种材料放在魔盒中合成，会开启最终BOSS传送门通往 *混沌崔斯特瑞姆*。
* 在 *混沌崔斯特瑞姆* 中击败 *超级墨菲斯托*、*超级暗黑破坏神* 以及 *超级巴尔* 之后，会掉落一个未鉴定的暗金大护身符，鉴定后就是火炬了。

6BOSS有一定的难度，可能要单独搭配一个挑战6BOSS的BD。 一般来说能够挑战 <<big-black,大黑>> 的BD，也能打得过6BOSS。

掉落的火炬具体加的是哪个职业的技能是随机的，所以可能要多次挑战6BOSS。 当然也可以与其它玩家进行交易，用自己不需要的火炬交换到自己所需的。

[[small-black]]
== 超级暗黑破坏神(小黑)

小黑和原版掉落毁灭小护身符的黑毛，虽然长得一样，但是触发条件和掉落有所不同。

=== 触发条件

小黑触发条件分两种：

* 第一种个人房间在向商店出售暗金或绿装的时候，有5%的几率触发。这种是最为常见的。
* 第二种是全服共同计算，同样是出售暗金或绿装，达到200-10000件的时候，随机触发。这种不可控，一般可以忽略，遇到了更好没遇到也无所谓。

=== 小黑掉落

小黑可以掉落符文(19-28#)、打孔盒子/碎片、轻歌之瓶(装备转无形道具)、莉莉丝的镜子(复制道具)、无限钥匙、无限回程、无限鉴定、完美宝石、世界之石碎片、一次性手工配方等。

=== 说明

小黑事件触发后，屏幕上方会滚动飘过一行通知：暗黑破坏神出现在地表上。

玩家下一次遇到特殊精英怪的时候，这只怪会被替换为小黑。具体有哪些怪物可以替换，可以查看 https://wiki.projectdiablo2.cn/wiki/Zones[Wiki->区域->区域等级表格,window=_blank] 中最后一列的特殊怪物。这里还有一份 https://wap.gamersky.com/gl/Content-1428532.html[暗黑原版场景等级以及金怪对照,window=_blank] 可以作为参考。

如果小黑触发之前怪物就已经被玩家探索到了，这只怪就不会被替换了。换句话说如果你在触发小黑之前已经“遇见”这只精英怪，哪怕是没有亲眼看到，但是在同一场景，系统判定你已经遇见了，那么触发小黑后这只精英怪就一定不会转换成小黑了。

一般推荐去A5第一个小站那里找小黑，因为传送点上方特别近的地方就有一只特殊怪物-矫正者，距离特别近，找起来比较方便。

打完小黑后建议立刻退出房间重建，否则可能会影响正常剧情或出现其它BUG。尤其是A4混沌庇护所，可能会刷不出来BOSS。

开荒期间玩家装备较差，打不过小黑的时候，建议将暗金和绿装存起来，留着以后角色强度上来了再出售触发。

NOTE: 由于装备太多会导致仓库格子占用太大，建议用魔盒公式 __**钥匙+暗金/绿装**__ 的公式将装备转换成一件绿色套装项链，这样可以节省大量仓库空间。

这里提供一个我在S9赛季录制的 https://b23.tv/v5mdURA[陨石法师刷小黑,window=_blank] 的视频当作参考。

[[big-black]]
== 超级暗黑破坏神(大黑)

大黑是游戏中非常强大的BOSS，其掉落的毁灭小护身符对角色提升非常重要。

=== 门票获取

大黑的传送门通过门票 *恐怖异象* 开启，门票合成材料包括下面三种：

* 原罪之魂：地狱难度A3BOSS墨菲斯托(劳模)4.76%/A4BOSS暗黑破坏神(大菠萝)6.25%/A5BOSS巴尔10%
* 黑色灵魂石：混沌崔斯特瑞姆（6boss最终红门）的BOSS（每个BOSS12%几率）
* 纯粹的恶魔精髓：地图BOSS（2%）

拥有门票后，在A5哈洛加斯城镇中的血喷泉(就是安雅左边的那个红盆)附近右键使用后进入。

=== 难度和掉落

击败大黑后会必定掉落一个暗金的小护身符，鉴定后就是毁灭小符(USC)了。

毁灭小符提供全技能+1的强大效果、5-10%的经验加成，还有体力、精力和抗性词条。

门票 *恐怖异象* 可以在魔盒中自由切换难度，难度有L0、L1、L2三种。 默认难度为L0，即为简单难度。

切换为L1或L2后，难度会逐渐提升，同时会有几率掉落额外的BOSS专属物品，L1掉落率为1:220，L2为1:100。

=== 战斗建议

大黑的详细机制在 https://wiki.projectdiablo2.cn/wiki/Monsters#%E9%95%9C%E5%83%8F%E5%A4%A7%E8%8F%A0%E8%90%9D%EF%BC%88%E5%A4%A7%E9%BB%91%E6%AF%9B%EF%BC%89Diablo-Clone[wiki,window=_blank] 中有介绍，这里只做几点说明：

* 进入战斗后玩家从外面带来的全部BUFF会被清空，需要重新开启。
* 雇佣兵会被暂时移除不生效。
* 无法自由退出场景。战斗胜利后会开启一个传送门供我们自由进出。
* 大黑转阶段的时候，脚下会有个五彩光环，和圣骑士的救助光环类似。此时大黑会进入无敌状态，免疫全部伤害，此时打他是不掉血的。
* 当大黑脚下踩着无敌光环往中间跑的时候，说明他要放大招了，一定要远离大黑至少10码以上，否则会被秒杀。
* 因为战斗中不能回城，所以背包一定要装满大紫，包括赫拉迪克方块里面也装满。在战斗中丢掉方块，方块里面的药水会自动全部进入背包。

这里提供一个我在S9赛季录制的 https://b23.tv/6datxH2[狂怒德鲁伊打L0大黑,window=_blank] 的视频当作参考。

[[rathma]]
== 拉斯玛(大马)

拉斯玛和门德利是PD2中新增的两个BOSS，难度很高。

战斗胜利会掉落一块暗之世界石碎片，可以对毁灭小护身符进行腐化。运气好的话可能会出现+1全部技能的效果。

=== 门票获取

大马的传送门通过门票 *虚空石* 开启，门票合成材料包括下面三种：

* 虚空碎片：掉落于地图特殊事件Shadow of Mendeln门德利之影（40%几率）
* 塔格奥的下颌骨：掉落于不死的敌人（地狱难度1:22.5K几率）
* 火炬灰烬：就是 <<six-boss,6boss>> 掉落的火炬的可堆叠形式，找一个垃圾火炬转换即可

拥有门票后，在A5哈洛加斯城镇中的血喷泉(就是安雅左边的那个红盆)附近右键使用后进入。

=== 难度和掉落

门票 *虚空石* 可以在魔盒中自由切换难度，难度有L0、L1、L2三种。 默认难度为L0，即为简单难度。

除了暗之世界石碎片外，还有1:200的几率掉落一件专属物品，以及1:66的几率掉落一本书籍(赫拉迪姆引导-无限回城，赫拉迪姆编年史-无限鉴定)。

切换为L1或L2后，难度会逐渐提升，同时会有额外的几率掉落BOSS专属物品，L1掉落率为1:220，L2为1:100。
同时也有额外的几率掉落赫拉迪姆引导1:50、赫拉迪姆编年史1:48、无限钥匙1:46。

=== 参考视频

这里提供一个我在S9赛季录制的 https://b23.tv/UG0spKz[狂怒德鲁伊打L0大马,window=_blank] 的视频当作参考。

== 参考资料

* link:https://www.reddit.com/r/ProjectDiablo2/comments/mrsf67/guide_endgame_basics_to_pd2[reddit帖子:[Guide\] End-Game Basics to PD2,window=_blank]
* link:https://wiki.projectdiablo2.cn/wiki/%E9%A6%96%E9%A1%B5[PD2国服Wiki,window=_blank]
* link:https://qm.qq.com/cgi-bin/qm/qr?k=cgdOh0UaPRz1bEBBG3-o9EQVtkq6cSgv&jump_from=webapi[QQ群(693091795),window=_blank] 内大佬指点
