= 萌新指北

本章将简略介绍PD2中的主要玩法，给萌新一个入门引导。

== 手工

手工就是根据配方合成装备，允许在固定几条词缀的基础上随机分配其他词缀，手工是原版暗黑破坏神2毁灭之王(LoD)就有的系统。

需要注意的是，PD2在原版的基础上对手工合成进行了很多优化。例如:

* 不再限制装备底材，无论是什么底材的装备都能使用该装备部位的任意配方；
* 黄金物品也能使用手工配方进行合成；
* 添加了一些新的手工配方：吸血、丰饶、闪耀。

使用手工配方可以在游戏前期轻松合成基础装备，一些合(海)理(景)搭(房)配词缀的手工装备更是能成为某些BD的毕业(GG)装备。

详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Crafting[手工介绍,window=_blank]。

== 腐化

腐化是PD2新增的内容，类似 https://poe.qq.com[POE(流放之路),window=_blank] 的“瓦尔系统”，需要消耗世界之石碎片在魔盒内进行合成。

详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Corruptions[腐化介绍,window=_blank]。

需要注意的是，腐化不光可以针对装备，也可以针对T图。

同时，毁灭小护身符也可以进行腐化，不过所需材料是拉斯玛(俗称"大马")掉落的"暗之世界石碎片"。

== 我应该刷哪？

刷刷刷是暗黑like游戏的核心，在接触一款暗黑like游戏时，萌新最开始要了解的就是应该刷哪里。

这里推荐一些热门地点：

* BD成型前的farm地点
** 噩梦BOSS
** 地狱A2BOSS督瑞尔(法师卡位杀)
** 地穴(地狱-A1泰摩高地的洞穴)
** 矫正者/督军山客(噩梦/地狱-A5第一个传送点上下两波怪)
** 古代通道(地狱-A2失落城市洞穴)(冰法)
** 冥河之洞(A5亚瑞特高原红门)(电系)
* 有一定装备基础后的farm地点
** 地狱超市(A4混沌庇护所)
** 地狱牛场(通关后A1用怀特假腿和回城卷合成红门)
** 地狱巴尔(A5毁灭王座)
** T1地图
** 组队刷T2/T3地图
* 游戏后期的farm和挑战
** T3地图(包括暗金地图)
** <<new-3bb,超级古代人(新3BB)>>
** <<six-boss,超级崔斯特瑞姆(6BOSS)>>
** <<big-black,超级暗黑破坏神(大黑)>>
** <<rathma,拉斯玛和门得利(大马)>>
** T4地图

需要注意的是，在PD2中，A1BOSS安达利尔(俗称安姐)使用的是A3BOSS墨菲斯托相同的掉落； A2BOSS督瑞尔(虫子)使用的是A5BOSS巴尔相同的掉落。

而由于法师在前期可以卡位无伤杀虫子，虫子又和巴尔相同掉落。 所以法师在开荒的时候，用火墙卡位刷虫子(地狱)是前期积累基础装备(俗称日用品)的一个非常好的选择。

[[map]]
== 地图

地图(俗称T图)，是PD2新增的内容，类似 https://poe.qq.com[POE(流放之路),window=_blank] 的“异界地图系统”，是游戏中很重要的一个farm场景。 详情请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Maps[地图介绍,window=_blank]。

T图分为T1、T2、T3以及极难的T4四个等级。场景等级分别为87/88/89/90级。 T图与原版游戏相比，区域等级更高，能够出游戏的全部物品，所以也是游戏后期主要的farm场景。

一般来说，打造能够效率单刷T图(T3+亮金+腐化)的BD，是玩家在游戏前中期的一个重要目标。

=== 地图进入条件

80级以上，并且击败过原版剧情中的远古野蛮人(3BB)的角色，在A5城镇中右键点击地图，即可打开特殊地图的传送红门。

每局游戏中只能开启一个地图，在刷完之后需要重建房间再次开启。

=== 地图的获取

从噩梦难度第五幕起，精英怪开始有几率掉落T图；第一次完成地狱难度救安雅的任务后，也会固定赠送一张T1难度的地图。

在地图中打怪更容易掉落地图，也有几率出现更高级别的地图。

一般来说，一旦你开始farm地图，地图就不会缺少了(起码T1地图是这样-_-!)，一般不需要去野外找精英怪刷地图。

=== 地图修改

地图的词缀系统非常复杂，请查看Wiki上的 https://wiki.projectdiablo2.cn/wiki/Maps[地图介绍,window=_blank]。

一般我们会刷**T3+亮金+腐化**这样的地图，同时避免随机到那些困难的词缀。

如果一张地图有一些我们不想面对的词缀，我们也可以通过 *毁灭法珠* 将地图还原成白色普通地图重新进行修改，详情请查看 https://wiki.projectdiablo2.cn/wiki/Recipes#%E5%9C%B0%E5%9B%BE[Wiki->合成->消耗品->地图] 章节。

有些BD针对单体怪物的能力较强，AOE能力却比较弱势，这时候可以用道具 *强化法珠* (安雅处购买)与该地图在魔盒中进行合成。
合成后地图的怪物数量减半，获得的奖励翻倍，同时怪物也会适当的加强，但不会影响地图的事件。

[[new-3bb]]
== 超级古代人(新3BB)

原版亚瑞特山脉巅峰马道克、塔里克和科里克这3个野蛮人一般被玩家称为3BB，PD2以之为蓝本新增了一个场景。

新3BB与原版相比更为强大，同时增加了掉落(原版是没有掉落的)。

新3BB可以在开始战斗前切换雕像，选择与哪几个野蛮人进行战斗。在战斗胜利后，每个野蛮人会掉落一个英雄旗帜。

新3BB难度较高，奖励也极其丰富，会掉落大量装备包括暗金和套装，是游戏中后期不能错过的farm场景。
https://b23.tv/LGKzmwH[这里,window=_blank] 是我在S9赛季录制的一场3BB视频。

NOTE: 据我个人的不准确观测，新3BB掉落“大货”的几率很高。像技能腰带、4神器这种爆率较低的物品，在新3BB经常掉落，上面链接中的视频就掉落了“次元”。

=== 如何进入

进入3BB需要提前准备好 *古代人的遗物* ，也就是门票，在A5哈洛加斯城镇中的血喷泉(就是安雅左边的那个红盆)附近右键使用后进入。

*古代人的遗物* 是T1、T2以及T3<<map,地图>>中分别掉落的三种印记，在魔盒中合成出来的。三种印记的掉落几率是：

* *马道克的印记*：T1地图怪物1:12K几率掉落
* *塔里克的印记*：T2地图怪物1:10K几率掉落
* *科里克的印记*：T3地图怪物1:8K几率掉落

[[six-boss]]
== 超级崔斯特瑞姆(6BOSS)

6BOSS是原版就有的系统，击败最终BOSS后会获得 *火炬* 护身符，增加随机职业的2点技能，是游戏中非常重要的物品，基本上每个BD都需要它。

由于整个流程需要与6个BOSS进行战斗，所以被玩家称为6BOSS。

=== 门票获取

PD2针对6BOSS做出了一些优化。

首先就是增加了掉落门票的怪物：

* *恐惧之钥*：女伯爵(A1-遗忘之塔)1:11几率掉落、血鸦(A1-埋骨之地)1:9几率掉落
* *憎恨之钥*：召唤者(A2-神秘庇护所)1:8几率掉落、疯狂血腥女巫(A2-死亡之殿第三层)1:9几率掉落
* *毁灭之钥*：尼拉塞克(A5-安雅红门)1:8几率掉落、衣卒尔(A4-绝望平原)1:9几率掉落

其次在 *地图-黑暗尖塔* 事件中会有几率掉落钥匙，每张地图最多掉落6把钥匙。
这也是我最推荐的farm钥匙的途径，因为你可以在farmT图的过程中顺便就刷到了钥匙。

=== 6BOSS流程

* 当我们分别获取3种钥匙各3把，也就是一共9把钥匙后，就可以开启6BOSS战斗了。
* 在地狱难度A5哈洛加斯城镇中开启，开启办法是将任意3种钥匙各1把，放在魔盒中合成，即可开启一个红色传送门。
红色传送门有3种，分别是 *痛苦熔炉(BOSS为混沌衣卒尔)*、*主母巢穴(BOSS为莉莉丝)*、*遗忘沙漠(BOSS为混沌督瑞尔)*，打开哪个传送门是随机的，但在同一局游戏中不会重复出现。所以我们一般会在同一局游戏中开启这三个红门。
* 分别击败这三个BOSS，**衣卒尔**会掉落**墨菲斯托之脑**，**莉莉丝**会掉落**暗黑破坏神之角**，**督瑞尔**会掉落**巴尔之眼**。将这三种材料放在魔盒中合成，会开启最终BOSS传送门通往 *混沌崔斯特瑞姆*。
* 在 *混沌崔斯特瑞姆* 中击败 *超级墨菲斯托*、*超级暗黑破坏神* 以及 *超级巴尔* 之后，会掉落一个未鉴定的暗金大护身符，鉴定后就是火炬了。

6BOSS有一定的难度，可能要单独搭配一个挑战6BOSS的BD。
一般来说能够挑战 <<big-black,大黑>> 的BD，也能打得过6BOSS。

掉落的火炬具体加的是哪个职业的技能是随机的，所以可能要多次挑战6BOSS。
当然也可以与其它玩家进行交易，用自己不需要的火炬交换到自己所需的。

[[big-black]]
== 超级暗黑破坏神(大黑)

[[rathma]]
== 拉斯玛和门得利(大马)

== T4地图

1111

- 手工
- 腐化
- 刷哪
- 装备成型前
- 噩梦BOSS
- 地穴(地狱)
- 矫正者/督军山客(噩梦/地狱)
- 古代通道(地狱)(冰法)
- 冥河之洞(电系)
- 成型后
- 地狱超市
- 地狱牛场
- 地狱巴尔
- T1地图
- 组队刷T2/T3地图
- 地图
- 新3BB
- 6BOSS
- 女伯爵(A1-遗忘之塔)、血鸦(A1-埋骨之地)
- 召唤者(A2-神秘庇护所)、疯狂血腥女巫(A2-死亡之殿第三层)
- 尼拉塞克(A5-安雅红门)、衣卒尔(A4-绝望平原)
- 大黑毛
- 拉斯玛

== 参考资料

* link:https://www.reddit.com/r/ProjectDiablo2/comments/mrsf67/guide_endgame_basics_to_pd2[reddit帖子:[Guide\] End-Game Basics to PD2,window=_blank]
* link:https://wiki.projectdiablo2.cn/wiki/%E9%A6%96%E9%A1%B5[PD2国服Wiki,window=_blank]
* link:https://qm.qq.com/cgi-bin/qm/qr?k=cgdOh0UaPRz1bEBBG3-o9EQVtkq6cSgv&jump_from=webapi[QQ群(693091795),window=_blank] 内大佬指点
